---
k3s-server:
  hosts:
    k3s-server-[1:3]:

k3s-agent:
  hosts:
    k3s-agent-[1:6]:

k3s-all:
  children:
    k3s-server:
    k3s-agent:

# techno_tim.k3s_ansible - servers
master:
  children:
    k3s-server:

# techno_tim.k3s_ansible - agents 
node:
  children:
    k3s-agent: